Repository wanted-running-sheep/dasheep-board, pull requests merged in 2022-07, with the labels that each got.

#6 💄 style: Navigation, Header 생성
  package-lock.json
  package.json
  src/components/Header.tsx
  src/components/Layout.tsx
  src/index.tsx
  src/pages/DashboardPage.tsx
  src/pages/ManagementPage.tsx
Labels: 📱 UI

#13 ✨ feat: 데이터 페칭 모듈 수정 및 대시보드 화면 구현
  database/db.json
  package-lock.json
  package.json
  src/@types/api.d.ts
  src/api/http/httpRequest.ts
  src/api/models/useAdvertisementModel.ts
  src/api/models/useMediaModel.ts
  src/api/models/useReportModel.ts
  src/api/models/useTotalDataManagement.ts
  src/components/DropDownMenu/index.tsx
  src/components/Report/Summary.tsx
  src/components/Report/SummaryCard.tsx
  src/components/Report/index.tsx
  src/pages/DashboardPage.tsx
  src/utils/createWeekList.ts
  src/utils/dateFormat.ts
Labels: 🕹️ 기능

#11 ✨ feat: drawer 메뉴 토글 기능 추가
  src/@types/styled.d.ts
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/NavigationBar.tsx
  src/constants/index.ts
  src/hooks/useDrawer.ts
  src/pages/ManagementPage.tsx
  src/pages/index.tsx
  src/routes/index.tsx
Labels: 🕹️ 기능

#16 ✨ feat: Navigation, Header, SummaryCard 컴포넌트 수정
  package-lock.json
  package.json
  src/components/AdvertisingCrad.tsx
  src/components/AdvertisingStatus.tsx
  src/components/DropDownMenu/index.tsx
  src/components/Dropdown.tsx
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/Layout/Header.tsx
  src/components/Layout/NavigationBar.tsx
  src/components/Layout/Title.tsx
  src/components/Layout/index.tsx
  src/components/MediaStatus.tsx
  src/components/NavigationBar.tsx
  src/components/Report.tsx
  src/components/Report/Summary.tsx
  src/components/Report/SummaryCard.tsx
  src/components/Report/index.tsx
  src/constants/index.ts
  src/hooks/useDrawer.ts
  src/index.tsx
  src/pages/DashboardPage.tsx
  src/pages/ManagementPage.tsx
  src/pages/index.tsx
  src/routes/index.tsx
  src/styles/media.ts
  src/styles/mixins.ts
  src/styles/theme.ts
  src/utils/findClickedMenu.ts
Labels: 📱 UI, 🕹️ 기능

#25 ✨ feat: 매체현황 주간 그래프 추가
  src/components/MediaStatus.tsx
  src/hooks/useFormattedMedia.ts
  src/pages/DashboardPage.tsx
Labels: 🕹️ 기능

#28 ✨ feat: 매체현황 주간 테이블 추가
  src/components/MediaStatusTable.tsx
Labels: 📱 UI, 🕹️ 기능

#26 ✨ feat: 광고관리 페칭된 데이터 가공하여 화면에 보여지도록 구현
  database/db.json
  src/@types/api.d.ts
  src/api/models/useTotalDataManagement.ts
  src/components/Management.tsx
  src/components/ManagementForm.tsx
  src/components/ManagementHeader.tsx
  src/components/ManagementInput.tsx
  src/constants/index.ts
  src/pages/DashboardPage.tsx
  src/pages/ManagementPage.tsx
  src/styles/globalStyles.ts
  src/utils/getCommaLocalString.ts
Labels: 📱 UI, 🕹️ 기능

#32 ♻️ refactor: 숫자 3자리마다 콤마, 소수점, 단위 변환 유틸 추가
  src/hooks/useSummaryData.ts
  src/utils/putCommaIntoNumber.ts
Labels: ⬆️ 리팩토링

#34 ✨ feat: 새로운 광고 등록 개발
  database/db.json
  src/api/models/useAdvertisementModel.ts
  src/components/Dropdown.tsx
  src/components/Management.tsx
  src/components/ManagementForm.tsx
  src/components/ManagementHeader.tsx
  src/components/ManagementInput.tsx
  src/constants/index.ts
  src/pages/DashboardPage.tsx
  src/utils/adsFormValidate.ts
  src/utils/getNewId.ts
  src/utils/makePropsAdvertisement.ts
  src/utils/makeViewData.ts
  src/utils/setPostReqVal.ts
Labels: 🕹️ 기능

#36 💄 style: 반응형 차트 옵션 추가
  src/components/AdvertisingStatus.tsx
  src/components/MediaStatus.tsx
Labels: 📱 UI

#35 ♻️ refactor: 매체 현황 데이터 포맷 변경 및 디자인 수정
  src/@types/media.d.ts
  src/components/MediaStatus.tsx
  src/components/MediaStatusTable.tsx
  src/constants/media.ts
  src/hooks/useFormattedMedia.ts
  src/styles/theme.ts
  src/utils/putCommaIntoNumber.ts
Labels: 📱 UI, ⬆️ 리팩토링

#38 ♻️ refactor: 버그 수정 및 코드 리팩토링
  src/@types/api.d.ts
  src/api/models/useAdvertisementModel.ts
  src/api/models/useMediaModel.ts
  src/api/models/useReportModel.ts
  src/components/Management.tsx
  src/components/ManagementButton.tsx
  src/components/ManagementForm.tsx
  src/components/ManagementInput.tsx
  src/hooks/useManagement.ts
  src/pages/ManagementPage.tsx
  src/utils/createRenderAds.ts
  src/utils/getNewId.ts
  src/utils/makeViewData.ts
  src/utils/setPostReqVal.ts
Labels: 🐞 버그, ⬆️ 리팩토링

#40 💄 style: 광고 관리 및 대시 보드 모바일 레이아웃 수정 및 폰트 적용
  src/assets/font.css
  src/components/AdvertisingCard.tsx
  src/components/AdvertisingStatus.tsx
  src/components/CalendarInput.tsx
  src/components/Dropdown.tsx
  src/components/Layout/Header.tsx
  src/components/Layout/NavigationBar.tsx
  src/components/Layout/Title.tsx
  src/components/Layout/index.tsx
  src/components/Management.tsx
  src/components/ManagementForm.tsx
  src/components/ManagementHeader.tsx
  src/components/ManagementInput.tsx
  src/components/MediaStatus.tsx
  src/components/MediaStatusTable.tsx
  src/components/Report.tsx
  src/hooks/useDrawer.ts
  src/styles/globalStyles.ts
  src/styles/media.ts
  src/styles/mixins.ts
  src/styles/theme.ts
Labels: 📱 UI, 🕹️ 기능

#43 🐛 fix: 사파리 브라우저에서 인식 못하는 정규 표현식 수정
  src/utils/putCommaIntoNumber.ts
Labels: 🐞 버그
